/*
 * Copyright (c) 2026 Tomarun029831
 * SPDX-License-Identifier: MIT
 */
// IWYU pragma: private, include <kic_notation.h>
#pragma once
#include "kic_timestamp.h"
#include <stddef.h>
#include <stdint.h>

#define KIC_COMPATIBLE ((unsigned char)0)
#define KIC_INCOMPATIBLE ((unsigned char)1)
/**
 * @brief Checks if the string is compatible with the supported KIC notation
 * version.
 * * @param[in] string Null-terminated string to verify.
 * @return KIC_COMPATIBLE if compatible, KIC_INCOMPATIBLE otherwise.
 */
const unsigned char check_kic_compatibility(const char *string);

#define KIC_SYNTAX_CORRECT ((unsigned char)0)
#define KIC_SYNTAX_ERROR ((unsigned char)1)
/**
 * @brief Validates the syntax of the KIC string. Internally calls
 * check_kic_compatibility().
 * * @param[in] string Null-terminated string to validate.
 * @return KIC_SYNTAX_CORRECT on success, KIC_SYNTAX_ERROR on failure.
 */
const unsigned char check_kic_syntax(const char *string);

/**
 * @brief Extracts a timestamp from the KIC data string.
 * * @param[in] string KIC formatted string.
 * @return KIC_Timestamp The extracted timestamp structure.
 * @pre The string must be validated using check_kic_syntax() before calling
 * this function to ensure data integrity.
 */
const KIC_Timestamp get_kic_timestamp(const char *string);

typedef struct {
  const uint16_t height_cm;
  const uint16_t width_cm;
} BoardSize;
#define BOARDSIZE(h, w) ((BoardSize){(h), (w)})
/**
 * @brief Extracts the board dimensions (height and width).
 * * @param[in] string KIC formatted string.
 * @return BoardSize Dimensions in centimeters.
 * @pre The string must be validated using check_kic_syntax() before calling
 * this function.
 */
BoardSize get_kic_boardsize(const char *string);

typedef const char *KIC_SchedulePtr;

#define KIC_SCHEDULE_NOT_FOUND ((const char *)0) // HACK:
/**
 * @brief Searches for a schedule starting point for a specific day of the week.
 * * @param[in] string KIC formatted string.
 * @param[in] day    Target day character (e.g., '0' to '6').
 * @return KIC_SchedulePtr Pointer to the start of the schedule. Returns
 * KIC_SCHEDULE_NOT_FOUND if not found.
 * @pre The string must be validated using check_kic_syntax() before calling
 * this function.
 */
KIC_SchedulePtr find_kic_schedule(const char *string, const char day);

#define KIC_TIME_NOT_FOUND (TIMESTAMP_RAW(0, 0, 0, 1))
/**
 * @brief Retrieves a specific timestamp from a schedule block by index.
 * * @param[in] ptr_to_schedule Pointer returned by find_kic_schedule().
 * @param[in] idx             The index of the time entry (starting from 0).
 * @return KIC_Timestamp The timestamp entry. Returns KIC_TIME_NOT_FOUND
 * (is_invalid=1) if out of bounds.
 * @note This function relies on the pointer generated by find_kic_schedule().
 */
const KIC_Timestamp find_kic_time_in_schedule(KIC_SchedulePtr ptr_to_schedule,
                                              const size_t idx);
