/*
 * Copyright (c) 2026 Tomarun029831
 * SPDX-License-Identifier: MIT
 */
// IWYU pragma: private, include "kic_notation.h"
#pragma once
#ifdef ARDUINO
#include "../kic_timestamp/kic_timestamp.h"
#else
#include "kic_timestamp.h"
#endif // ARDUINO
#include <stddef.h>
#include <stdint.h>

#define KIC_COMPATIBLE ((unsigned char)0)
#define KIC_INCOMPATIBLE ((unsigned char)1)
const unsigned char check_kic_compatibility(const char *string);

#define KIC_SYNTAX_CORRECT ((unsigned char)0)
#define KIC_SYNTAX_ERROR ((unsigned char)1)
// this function will call check_kic_compatibility() with the argument
const unsigned char check_kic_syntax(const char *string);

// this function will NOT check the syntax,
// So you need to call check_kic_syntax(const char *string),
// if you cannot ensure that the argument of this function follows kic-format
const KIC_Timestamp get_kic_timestamp(const char *string);

typedef struct {
  const uint16_t height_cm;
  const uint16_t width_cm;
} BoardSize;
#define BOARDSIZE(h, w) ((BoardSize){(h), (w)})
// this function will NOT check the syntax,
// So you need to call check_kic_syntax(const char *string),
// if you cannot ensure that the argument of this function follows kic-format
BoardSize get_kic_boardsize(const char *string);

typedef const char *KIC_SchedulePtr;

#define KIC_SCHEDULE_NOT_FOUND ((const char *)0) // HACK:
// this function will NOT check the syntax,
// So you need to call check_kic_syntax(const char *string),
// if you cannot ensure that the argument of this function follows kic-format
KIC_SchedulePtr find_kic_schedule(const char *string, const char day);

#define KIC_TIME_NOT_FOUND (TIMESTAMP_RAW(0, 0, 0, 1))
// this function will NOT check the syntax,
// So you need to call check_kic_syntax(const char *string),
// if you cannot ensure that the argument of this function follows kic-format.
// the function depends on result which is generated by find_kic_schedule(...)
const KIC_Timestamp find_kic_time_in_schedule(KIC_SchedulePtr ptr_to_schedule,
                                              const size_t idx);
